### ISSUE TITLE
paramiko.ssh_exception.SSHException: not a valid RSA private key file

### ISSUE THREAD

**Issue by carrieyummy** [open-power-ref-design-toolkit/power-up#442]
MacOS Mojave，python3.7.2  ,paramiko 2.4.2, cryptography  2.4.2   
I created a private key:
`ssh-keygen -t rsa`
When I tried to load the key , I get some exception.
`key = paramiko.RSAKey.from_private_key_file(path)`
The exception:
```
Traceback (most recent call last):
  File "/Users/tianyawei/PycharmProjects/protocolTest/CUAdapterV1/AdapterMachine/Machine", line 154, in <module>
    run()
  File "/Users/tianyawei/PycharmProjects/protocolTest/CUAdapterV1/AdapterMachine/Machine", line 131, in run
    key = paramiko.RSAKey.from_private_key_file(path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/pkey.py", line 206, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/rsakey.py", line 55, in __init__
    self._from_private_key_file(filename, password)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/rsakey.py", line 175, in _from_private_key_file
    data = self._read_private_key_file("RSA", filename, password)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/pkey.py", line 279, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/pkey.py", line 289, in _read_private_key
    raise SSHException("not a valid " + tag + " private key file")
paramiko.ssh_exception.SSHException: not a valid RSA private key file
```
the openssh private key：
![image](https://user-images.githubusercontent.com/39080899/55216364-820bc880-5237-11e9-9a33-31a7d20da8d5.png)

Please help me.

**Comment by jaywcarman** [comment]
This is not a power-up issue, closing.

When reading a private RSA key from file Paramiko expects a header in the following format:
'-----BEGIN RSA PRIVATE KEY-----'

Your file does not have the expected header and thus Paramiko raises the `SSHException`:
https://github.com/paramiko/paramiko/blob/b5f4c213ba2e3b560cda84efc556812ff989cd1f/paramiko/pkey.py#L285-L289

I don't have any experience with generating SSH key pairs in MacOS so I'm not sure what's expected behavior.

**Comment by carrieyummy** [comment]
> This is not a power-up issue, closing.
> 
> When reading a private RSA key from file Paramiko expects a header in the following format:
> '-----BEGIN RSA PRIVATE KEY-----'
> 
> Your file does not have the expected header and thus Paramiko raises the `SSHException`:
> https://github.com/paramiko/paramiko/blob/b5f4c213ba2e3b560cda84efc556812ff989cd1f/paramiko/pkey.py#L285-L289
> 
> I don't have any experience with generating SSH key pairs in MacOS so I'm not sure what's expected behavior.

Thank you anyway
